import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen grid grid-cols-[260px_1fr] grid-rows-[56px_1fr]" data-theme="light">
          <aside className="row-span-2 bg-[var(--muted)] border-r border-[var(--border)] p-4">
            <div className="text-xl font-semibold mb-6">CRM</div>
            <nav className="space-y-2 text-sm">
              <NavLink href="/">Dashboard</NavLink>
              <NavLink href="/customers">Customers</NavLink>
              <NavLink href="/opportunities">Opportunities</NavLink>
              <NavLink href="/meetings">Meetings</NavLink>
              <NavLink href="/reports">Reports</NavLink>
              <NavLink href="/settings">Settings</NavLink>
            </nav>
          </aside>
          <header className="col-start-2 h-14 flex items-center gap-3 px-4 border-b border-[var(--border)]">
            <form className="flex-1">
              <input
                placeholder="Search..."
                className="w-full h-9 rounded-md px-3 bg-transparent border border-[var(--border)] focus:outline-none"
                aria-label="Global search"
              />
            </form>
            <ThemeToggle />
          </header>
          <main className="col-start-2 p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

function NavLink(props: { href: string; children: React.ReactNode }) {
  return (
    <Link
      href={props.href}
      className="block px-3 py-2 rounded-md hover:bg-[var(--border)]/30"
    >
      {props.children}
    </Link>
  );
}

function ThemeToggle() {
  return (
    <button
      type="button"
      className="h-9 px-3 rounded-md border border-[var(--border)]"
      onClick={() => {
        if (typeof document === "undefined") return;
        const root = document.documentElement;
        const isDark = root.getAttribute("data-theme") === "dark";
        root.setAttribute("data-theme", isDark ? "light" : "dark");
      }}
    >
      Theme
    </button>
  );
}
